name: Run Fuzzer on HTML Parser

on:
  push:
    branches:
      - main

jobs:
  run-fuzzer:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set Up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17' # Specify the Java version you want to use

    # Build the project (if applicable)
    - name: Build HTML Parser
      run: |
        ./gradlew build # Adjust to your build system (e.g., Maven or Gradle)
      
    # Compile the fuzzer
    - name: Compile Fuzzer
      run: javac -d . Fuzzer.java

    # Run the fuzzer
    - name: Run Fuzzer
      run: java Fuzzer html_parser
      continue-on-error: false # Workflow will fail if Fuzzer exits with a non-zero code

    # Debugging: View logs if it fails
    - name: Debug Logs
      if: failure()
      run: cat logs/output.log # Replace with the location of any logs your fuzzer generates

