name: Run Fuzzer on HTML Parser

on:
  push:
    branches:
      - main

jobs:
  run-fuzzer:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set Up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Verify file structure
    - name: Verify Files
      run: |
        ls -l

    # Grant execution permissions to the executable
    - name: Make Executable
      run: |
        chmod +x html_parser_linux_x86_64

    # Compile Java Files
    - name: Compile Java Files
      run: |
        javac -d . Fuzzer.java

    # Run the Fuzzer
    - name: Run Fuzzer
      run: |
        java Fuzzer ./html_parser_linux_x86_64
